name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install libcurl
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build project
        run: |
          cd build
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
